### ISSUE TITLE
Add Soundcloud Browser

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#1828]
This would be nice; Clementine has one as do a few other things.

Imagine it would be either similar (or even _an extension_) to the Internet Radio Browser. Obviously this would require users signing up.

There is a [lightweight API](https://developers.soundcloud.com/docs/api/guide#uploading) and everything.

Ideally this would be implemented using Browsers as plugins (see #157).

**Comment by nodiscc** [comment]
It would be a great addition. There is https://github.com/soundcloud/soundcloud-python -  A Python wrapper around the Soundcloud API. Do you know if one would be able to use this plugin (browsing/searching/playing soundcloud tracks) without a soundcloud user account?

**Comment by declension** [comment]
@nodiscc - no it would / will be account-only for now. The API is geared that way, and most of the interesting features come with that anyway. It wouldn't require a pro account anyway..

**Comment by declension** [comment]
Some experimental work in the [souncloud-browser branch](https://github.com/quodlibet/quodlibet/tree/soundcloud-browser).

Pretty rough still, but the authentication flow, basic UI, searching, and integration with QL is working (for me).

Needs the `soundcloud` module, though longer term might try to ditch that and use the GTK+ libraries.

**Comment by lazka** [comment]
> Some experimental work in the souncloud-browser branch.

Cool, got it working, kinda. Please tell if you want feedback.

> Needs the soundcloud module, though longer term might try to ditch that and use the GTK+ libraries.

As soundcloud isn't in debian (I think?) that would make it easier. On Windows/OSX shipping soundcloud from pypi isn't a problem.

**Comment by declension** [comment]
Good point. I've not used the Soup stuff but it looks OK so I'll try duplicating as little of the helper methods as needed to get it working.

And yes feedback would be useful.... in particular I'm debating how to integrate searching with QL in  a way that makes sense for a/any remote "library" of millions of tracks... that supports almost none of the querying we do... Currently it's keeping a local cache of results and then using normal filtering which feels "native" but will fail miserably with non-text searches...

**Comment by lazka** [comment]
Also have a look at util.thread.call_async() + if you want we can use requests instead of urllib. Might make the update to py3 easier anyway.

(I don't know what the API exposes..)
I'd just try to replicate the online version and only allow text queries, for starters.
Have a combobox selecting between Tracks/Playlists/People/Groups. + a sidebar containing the filters + the results for playlist/people/group search.

**Comment by declension** [comment]
Cool I'll have a look at the threading helpers, was on my TODO list. Happy to use `requests` especially if that

As to the UI, I'd pretty much decided to ditch people and groups - I don't think QL could provide muchthat the web app wouldn't do a lot better. Probably playlists too - though that's worth thinking through more still.

**Comment by lazka** [comment]
Sounds good.

I got somewhat confused with the current login state as it opened a browser, I logged in and then it said "Connecting..." forever. After trying that 3 times I noticed that QL seems to work regardless.
Better feedback and would help there, before the login and after.

What does registering with an account give us btw?

**Comment by declension** [comment]
### Todo list
- [ ] Reauthenticating expired tokens
- [ ] Tidy authentication in general - error handling.
- [ ] Ditch `soundcloud` module, reimplementing where necessary (using `Soup` / `requests`)
- [ ] Fixing side panel / filters to be useful: text, duration, favourites, (your) playlists
- [ ] (proper) asynchronous querying
- [ ] Acceptable integration with QL main (as plugin, leave as browser, enabled / disabled)

### Further ideas
- [ ] Writeable rating, add to Soundcloud playlist
- [ ] Additional search filters: (creation) date, tags
- [ ] Custom songlist - clickable URLs, download buttons, single-value rating / heart icon for ratings.
- [ ] New query syntax subset / evaluator to allow only Soundcloud-compatible search filters?
- [ ] One-click download - prefs could control how this gets named (with QL pattern ideally à la _Rename Files_)
- [ ] Integrate comments with QL bookmarks e.g. `1:57 User: This is my comment...`. Might have to limit the results here for big tracks.
- [ ] Plugin / button to upload a track in one go...

**Comment by declension** [comment]
Lots more support done, including some of the nice to haves, still kept in https://github.com/quodlibet/quodlibet/tree/soundcloud-browser for now

**Comment by declension** [comment]
It's merged. Bugs / additional features can go in new tickets, so closing this.
