### ISSUE TITLE
QL 5.0

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3465]
The proposed change
-------------------
QL version 5.0 is released 

Benefits of this change
-----------------------
* Everyone feels good about all the great things happening in QL for the last year or two
* Any big / riskier changes are included to give users and packagers an indication that "breaking" changes may be coming (hopefully not breaking anything though)

Checklist
------------
(please edit)

For planning (actually, we could also do this with Github Projects I think?), here are some ideas for what might want to be in first

### Nice to haves?
* [ ] A little more startup attention (still think a GTK Reveal on startup, and on wave-seekbar-ready would be cool :grin: )
* [ ] New screenshots? The current ones underselling some of our newer style / features I feel
* [ ] Some fixes for the user guide
* [ ] [#920 - Audio fading on startup / exit](https://github.com/quodlibet/quodlibet/issues/920) 
* [ ] [#1061 - saved search UI rethink](https://github.com/quodlibet/quodlibet/issues/1061)

### Already in

* [x] QL Python >= 3.7
* [x] Playlists now use XSPF
* [x] [#3346 - Datetime columns now human-readable](https://github.com/quodlibet/quodlibet/issues/3346)
* [x] All [these commits since 4.3.0](https://github.com/quodlibet/quodlibet/compare/release-4.3.0...master) (unless we release more 4.x)

**Comment by declension** [comment]
Oh, right _milestones_: created [5.0 milestone](https://github.com/quodlibet/quodlibet/milestone/15) too

**Comment by Ironbalden** [comment]
Hi, just my two cents, since this is not a point release shouldn't be time to do something about the whole TXXX debacle? A major release seems perfect to address this issue. Thanks for your work.

**Comment by declension** [comment]
That feels like a `10.0` at the rate it's progressing :disappointed:

**Comment by Ironbalden** [comment]
Yes, that one. I am fully aware that it's a major pita, but it is one of the oldest issues we have that frustrated lots of users.

**Comment by CreamyCookie** [comment]
>  New screenshots? The current ones underselling some of our newer style / features I feel

Fully agree!

I think it might be a good idea to have two screenshots. First a really simple one (to not scare away anyone) which should probably be similar to the [current screenshot](https://github.com/quodlibet/quodlibet/raw/master/docs/images/paned.png). Then one that shows QL with a combination of plugins and settings, to showcase the configurability, that is a large part of QL's identity (as mentioned in the [FAQ](https://quodlibet.readthedocs.io/en/latest/guide/faq.html#what-does-the-name-mean)). 

Both these should probably link to the [screenshot page](https://quodlibet.readthedocs.io/en/latest/screenshots.html) in the docs.

**Comment by slosd** [comment]
I'm wondering if it's feasible to require Gtk 4 with 5.0? That has [FilterListModel](https://docs.gtk.org/gtk4/class.FilterListModel.html) and [SortListModel](https://docs.gtk.org/gtk4/class.SortListModel.html) which would be useful for using FlowBox for the cover grid (See https://github.com/quodlibet/quodlibet/issues/2840)

**Comment by JacksonCampolattaro** [comment]
> I'm wondering if it's feasible to require Gtk 4 with 5.0? That has [FilterListModel](https://docs.gtk.org/gtk4/class.FilterListModel.html) and [SortListModel](https://docs.gtk.org/gtk4/class.SortListModel.html) which would be useful for using FlowBox for the cover grid (See #2840)

I've been thinking about that too; Quod Libet does use some deprecated Gtk 3 functionality, so I was looking at what it would take to remove it. A lot of the changes are trivial, but some deprecated functions have no clear analogues.

**Comment by carl-di-ortus** [comment]
It feels like there's still some years for 5.0 to appear. And since it is a major release, I would like to propose one major (possibly braking) change - queue handling.

Yes it's a hard topic, yes we are used to different behaviors, but apparently there is no clear vision in this project whether changes here are even welcome, or it is a truly "intended behavior"? I'm talking about #4157 for example, and a bunch of linked issues there. Sorting out this all Queue stuff would close at least 10-15 issues here, out of total 73 open with the search keyword "queue".

I have spend a couple of evenings inspecting the code. I understand that this is a task of at least a few hundreds of evenings worth (I wish I had that much...). I have identified some large parts of code that would become obsolete, and deduplicate. I believe there would also be some minuscule performance increases. But most importantly - this would define a clear vision for how items are queued/dequeued, how playlist will continue after queue. This would bring a lot of clarity not only for users (a selling point for the project, yeah... it's open source, but I mean attractiveness, and potential future generations of developers), but also for maintainers, as then there would be a clear distinction weather those long hanging queue issues are even welcome or not.

I would welcome a separate discussion about this, UX guidelines, and support from experienced developers in this project. I'm not promising much, but I would accept to volunteer to code (manage) all this (with help).

**Comment by afontenot** [comment]
@carl-di-ortus I wrote the bug report / proposal that you link, and I agree, although I don't know that this needs to be linked to 5.0 necessarily. There are plenty of large changes that happen in minor releases.

IMO the real issue here is one of expectations. Quod Libet is 20 year old software at this point, it predates the consolidation of every other music player on the "play now / play next / play last" queued playback model. Some people like the aspects of the current model (other than some significant pain points -- you can't browse to a new album without the play order breaking), others don't really care either way (not enough to work on it), and a few (like me) really want QL to adopt the same queue model used by everyone else, we just use QL for its extensibility around tagging and other nice features.

As you've noticed there's also a huge amount of technical debt related to playback. The basic design was pretty extensible but the result of having a simple play order model as the default means that everything else is implemented as hacks on top of hacks. I've contributed to this too, take a look at my [grotesque hack](https://github.com/quodlibet/quodlibet/pull/3947/files) to allow automatically playing songs added to the queue, e.g. with a double click.

To fix this properly (IMO), we need the following:

 * firm agreement among major contributors about what the goal is (I tried to take a step toward that in my proposal)
 * an official branch to work on removing the existing song list / play order code and replacing it with something that's more queue friendly
 * more feedback from users (like you) about what you'd like to see with respect to queued playback. Do you just want something that behaves exactly like Spotify / Auxio / Navidrome / Strawberry / Kodi / virtually every other application, or are there features of Quod Libet's playback system that you want to keep? Why are you using Quod Libet instead of one of those other applications? 

If this becomes an ongoing discussion, it's probably best to move it to a new issue or leave comments on my proposal: https://github.com/quodlibet/quodlibet/issues/4157
